import type { Metadata } from "next";
import { Inter, Mochiy_Pop_One } from "next/font/google";
import "../../globals.css";

import ToasterContext from "../../context/ToasterContext";
import AuthContext from "../../context/AuthContext";

const inter = Inter({ subsets: ["latin"] });
const mochiyPopOne = Mochiy_Pop_One({ weight: ["400"], subsets: ["latin"] });

export const metadata: Metadata = {
    title: "NCKU Eater Auth",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <>
            <html lang="en">
                <body className={`${mochiyPopOne.className} ${inter.className}`}>
                    <AuthContext>
                        <ToasterContext />
                        <main className="flex flex-row bg-dark-1">
                            <section className="main-container">
                                <section className="w-full max-w-4xl mx-auto">
                                    {children}
                                </section>
                            </section>
                        </main>
                    </AuthContext>
                </body>
            </html>
        </>
    );
}