import type { Metadata } from "next";
import "../../globals.css";

export const metadata: Metadata = {
    title: "NCKU Eater Auth",
    description: "Generated by create next app",
};

export default function AuthLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <>
            <main className="flex bg-dark-1 min-h-screen justify-center items-center">
                <section className="w-full max-w-4xl">
                    {children}
                </section>
            </main>
        </>
    );
}